POST http://localhost:8080/user
Content-Type: application/json

{
  "userName": "test",
  "firstName": "test",
  "lastName": "Test",
  "email": "test@gmail.com",
  "password": "test",
  "phone": "test",
  "userStatus": 1
}

###

POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "userName": "test",
  "password": "test"
}

###

GET http://localhost:8080/user/findAll
X-Token: e1c44e5f-9364-42ce-b108-8c07e46f2553

###

POST http://localhost:8080/pet
Content-Type: application/json

{
  "name": "testPet",
  "status": "AVAILABLE",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "category":
  {
    "name": "testCateg"
  }
}

###

POST http://localhost:8080/tag
Content-Type: application/json

{
  "name": "taaaag"
}

###

POST http://localhost:8080/store/order
Content-Type: application/json

{
  "petId": 1,
  "quantity": 1,
  "shipDate": "2021-02-02",
  "status": "APPROVED",
  "complete": false
}
